# ddasdaadadasdsdaddasdasUncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitAction' do
  # ddasdasasddsdadasdaComment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitAction
  pod 'SwiftLint'

  target 'GitActionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitActionUITests' do
    # Pods for testing
  end

end
