name: iOS CI

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]
  
jobs:
  build-and-UnitTest:
    runs-on: macos-latest
  
    env:
      XC_VERSION: ${{ '12.1' }}
      XC_WORKSPACE: ${{ 'BoostClusteringMaB/BoostClusteringMaB.xcworkspace' }}
      XC_SCHEME: ${{ 'BoostClusteringMaBTests' }}
    
    steps: 
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./BoostClusteringMaB
        run: pod install --repo-update
        shell: bash

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - name: Run Build and Unit Tests
        run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
